[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer-runs = 1
fs_permissions = [{ access = "read", path = "./script/input"}]

[profile.default.fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true
ignore = [
  "src/lib/ERC20.sol",
  "src/lib/PackedStringLib.sol",
  "src/lib/SafeERC20.sol"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
